version: '3'

services:
  frontend:
    build: ./letsplay
    image: ghcr.io/los-dos-coders/letsplay-frontend
    ports:
      - "80:80"
    container_name: frontend-docker
    restart: always
    links:
      - backend
  
  backend:
    build: ./letsplay-server
    image: ghcr.io/los-dos-coders/letsplay-backend
    ports:
      - "8000:8000"
    container_name: backend-docker
    restart: always