version: '3'

services:
  frontend:
    build: 
      context: ./letsplay
      args: 
        - DNS_DIGITALOCEAN_TOKEN=$DNS_DIGITALOCEAN_TOKEN
        - ENV=$ENV
    image: ghcr.io/los-dos-coders/letsplay-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: frontend-docker
    restart: always
    links:
      - backend

  backend:
    build: ./letsplay-server
    image: ghcr.io/los-dos-coders/letsplay-backend:latest
    ports:
      - "8000:8000"
    container_name: backend-docker
    restart: always
