name: Build and Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./letsplay
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} to test Frontend
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./letsplay/package-lock.json"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./letsplay-server
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} to test Backend
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: letsplay-server/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install Dependencies
        run: npm clean-install
        working-directory: e2e
      - name: Build Docker Containers
        run: docker compose build
      - name: Start up Docker Containers
        run: docker compose up -d
      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: e2e
      - name: Run Tests
        run: xvfb-run npx playwright test --browser=all
        working-directory: e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
      - name: Shut Down Container
        run: docker-compose down