name: Deploy

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/los-dos-coders/letsplay-frontend
            ghcr.io/los-dos-coders/letsplay-backend
      - name: Build Docker Image
        run: docker-compose build
      - name: Push the Docker Images to the repo
        run: docker-compose push
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: ignore
      - name: Get time on Host Machine via SSH
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'time'
      - name: Pull Frontend Image on Host Machine
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'docker pull ghcr.io/los-dos-coders/letsplay-frontend'
      - name: Pull Frontend Image on Host Machine
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'docker pull ghcr.io/los-dos-coders/letsplay-backend'
      - name: Create Docker Remote Context
        run: docker context create remote --docker "host=ssh://${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST }}"
      - name: Start Up Containers on Host Machine using the Remote Context
        run: docker --context remote compose up -d
